/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuppliersRouteImport } from './routes/suppliers'
import { Route as SummaryRouteImport } from './routes/summary'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SalesHistoryRouteImport } from './routes/sales-history'
import { Route as RefundsRouteImport } from './routes/refunds'
import { Route as PurchasesRouteImport } from './routes/purchases'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as PosRouteImport } from './routes/pos'
import { Route as DeskRouteImport } from './routes/desk'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as CashboxRouteImport } from './routes/cashbox'
import { Route as IndexRouteImport } from './routes/index'

const SuppliersRoute = SuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => rootRouteImport,
} as any)
const SummaryRoute = SummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesHistoryRoute = SalesHistoryRouteImport.update({
  id: '/sales-history',
  path: '/sales-history',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundsRoute = RefundsRouteImport.update({
  id: '/refunds',
  path: '/refunds',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchasesRoute = PurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const PosRoute = PosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskRoute = DeskRouteImport.update({
  id: '/desk',
  path: '/desk',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const CashboxRoute = CashboxRouteImport.update({
  id: '/cashbox',
  path: '/cashbox',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cashbox': typeof CashboxRoute
  '/categories': typeof CategoriesRoute
  '/customers': typeof CustomersRoute
  '/desk': typeof DeskRoute
  '/pos': typeof PosRoute
  '/products': typeof ProductsRoute
  '/purchases': typeof PurchasesRoute
  '/refunds': typeof RefundsRoute
  '/sales-history': typeof SalesHistoryRoute
  '/settings': typeof SettingsRoute
  '/staff': typeof StaffRoute
  '/summary': typeof SummaryRoute
  '/suppliers': typeof SuppliersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cashbox': typeof CashboxRoute
  '/categories': typeof CategoriesRoute
  '/customers': typeof CustomersRoute
  '/desk': typeof DeskRoute
  '/pos': typeof PosRoute
  '/products': typeof ProductsRoute
  '/purchases': typeof PurchasesRoute
  '/refunds': typeof RefundsRoute
  '/sales-history': typeof SalesHistoryRoute
  '/settings': typeof SettingsRoute
  '/staff': typeof StaffRoute
  '/summary': typeof SummaryRoute
  '/suppliers': typeof SuppliersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cashbox': typeof CashboxRoute
  '/categories': typeof CategoriesRoute
  '/customers': typeof CustomersRoute
  '/desk': typeof DeskRoute
  '/pos': typeof PosRoute
  '/products': typeof ProductsRoute
  '/purchases': typeof PurchasesRoute
  '/refunds': typeof RefundsRoute
  '/sales-history': typeof SalesHistoryRoute
  '/settings': typeof SettingsRoute
  '/staff': typeof StaffRoute
  '/summary': typeof SummaryRoute
  '/suppliers': typeof SuppliersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cashbox'
    | '/categories'
    | '/customers'
    | '/desk'
    | '/pos'
    | '/products'
    | '/purchases'
    | '/refunds'
    | '/sales-history'
    | '/settings'
    | '/staff'
    | '/summary'
    | '/suppliers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cashbox'
    | '/categories'
    | '/customers'
    | '/desk'
    | '/pos'
    | '/products'
    | '/purchases'
    | '/refunds'
    | '/sales-history'
    | '/settings'
    | '/staff'
    | '/summary'
    | '/suppliers'
  id:
    | '__root__'
    | '/'
    | '/cashbox'
    | '/categories'
    | '/customers'
    | '/desk'
    | '/pos'
    | '/products'
    | '/purchases'
    | '/refunds'
    | '/sales-history'
    | '/settings'
    | '/staff'
    | '/summary'
    | '/suppliers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CashboxRoute: typeof CashboxRoute
  CategoriesRoute: typeof CategoriesRoute
  CustomersRoute: typeof CustomersRoute
  DeskRoute: typeof DeskRoute
  PosRoute: typeof PosRoute
  ProductsRoute: typeof ProductsRoute
  PurchasesRoute: typeof PurchasesRoute
  RefundsRoute: typeof RefundsRoute
  SalesHistoryRoute: typeof SalesHistoryRoute
  SettingsRoute: typeof SettingsRoute
  StaffRoute: typeof StaffRoute
  SummaryRoute: typeof SummaryRoute
  SuppliersRoute: typeof SuppliersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/suppliers': {
      id: '/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof SuppliersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/summary': {
      id: '/summary'
      path: '/summary'
      fullPath: '/summary'
      preLoaderRoute: typeof SummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales-history': {
      id: '/sales-history'
      path: '/sales-history'
      fullPath: '/sales-history'
      preLoaderRoute: typeof SalesHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refunds': {
      id: '/refunds'
      path: '/refunds'
      fullPath: '/refunds'
      preLoaderRoute: typeof RefundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchases': {
      id: '/purchases'
      path: '/purchases'
      fullPath: '/purchases'
      preLoaderRoute: typeof PurchasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos': {
      id: '/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof PosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk': {
      id: '/desk'
      path: '/desk'
      fullPath: '/desk'
      preLoaderRoute: typeof DeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cashbox': {
      id: '/cashbox'
      path: '/cashbox'
      fullPath: '/cashbox'
      preLoaderRoute: typeof CashboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CashboxRoute: CashboxRoute,
  CategoriesRoute: CategoriesRoute,
  CustomersRoute: CustomersRoute,
  DeskRoute: DeskRoute,
  PosRoute: PosRoute,
  ProductsRoute: ProductsRoute,
  PurchasesRoute: PurchasesRoute,
  RefundsRoute: RefundsRoute,
  SalesHistoryRoute: SalesHistoryRoute,
  SettingsRoute: SettingsRoute,
  StaffRoute: StaffRoute,
  SummaryRoute: SummaryRoute,
  SuppliersRoute: SuppliersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
